申告チェック結果のページからの講義情報の取得
TitechAppProject/titech-kyomu-kit pull request #3
Opened 2022-08-26 15:03 UTC by temmie-v

napierさんと作業しました。
- リクエストの作成
    - リクエスト先は、`...PID1_1.aspx` が修士と学士の学生で表示内容に差があるそうなので `...PID1_3_1.aspx` の申告チェック結果を採用
- 取得したチェック結果のHTMLをparse
- 表から講義情報を取得
    - 申告チェックの `チェック内容` が `OK` でないものは外す実装です
    - 科目コードのハイフン以下の番号は省略せずそのまま送っています、そのためOCWとは異なる科目コードが出ます
- テストの作成

2022-08-26 15:10 UTC, nanashiki commented on Tests/TitechKyomuKitTests/TitechKyomuKitTests.swift
> +    func testParseReportCheckPage() async throws {
Testケースは日本語と英語でfunc分けてください

2022-08-26 15:11 UTC, nanashiki commented on Sources/TitechKyomuKit/TitechKyomu.swift
> +    public func parse(html: String) async throws -> [Course] {
この関数ってpublicにする必要ありますでしょうか？

2022-08-26 15:11 UTC, nanashiki commented on Sources/TitechKyomuKit/TitechKyomu.swift
> +
必要ないスペースコミット入ってそう

2022-08-26 15:19 UTC, nanashiki commented on Sources/TitechKyomuKit/TitechKyomu.swift
> +    public func parse(html: String) async throws -> [Course] {
今後講義以外のparse も実装するかもなので関数名はもう少し講義をparseすることが分かりやすいものにしてもらえると助かります 🙏

2022-08-26 15:28 UTC, nanashiki requested changes
```swift
public func fetchRegisteredCoursePage() async throws -> String
```

はHTML返してると思いますが、このライブラリ使う側がHTMLを取得する必要はないので

```swift
public func fetchRegisteredCourses() async throws -> [Course]
```
として欲しいです

2022-08-26 15:29 UTC, nanashiki commented
あとCourseという型名もライブラリ使う側で被ることが多そうなのでKyomuCourseという型名に変えていただけると助かります 🙏

2022-08-26 16:03 UTC, temmie-v commented
- Course -> KyomuCourse に変えました
- TitechKyomu 内の関数について
    - parse の命名を変え、internal にしました
    - fetch を fetchKyomuCourseData として、この関数から `[KyomuCourse]` が返ってくるようにしました

2022-08-26 16:07 UTC, temmie-v commented on Sources/TitechKyomuKit/TitechKyomu.swift
> +
これだけ自動整形で毎回すぐ戻っちゃいます... 消せますけどすぐ戻っちゃうかも

2022-08-26 16:31 UTC, nanashiki commented on Sources/TitechKyomuKit/TitechKyomu.swift
> +
自動整形とはなんでしょうか？

Xcodeではないエディタ使ってます?
Swift の開発であればなるべくXcode使っていただけると 🙏

2022-08-26 16:32 UTC, nanashiki commented on Sources/TitechKyomuKit/TitechKyomu.swift
> +
Xcodeでも改行すると勝手にインデントスペース入るけど手動で消せば勝手に復帰することはないです(今後自動formatter入れようかな

2022-08-26 16:34 UTC, nanashiki commented on Sources/TitechKyomuKit/TitechKyomu.swift
> +    internal func parseReportCheckPage(html: String) async throws -> [KyomuCourse] {
すみません。internalって言ったけどinternalは通常書かないで省略します 🙇

2022-08-26 16:38 UTC, nanashiki commented
テストはTitechKyomu(mockHtml: html). fetchRegisteredCourses()をやってもらうことを意図してたけど、まあparse関数のみのテストでも必要十分感はあるなぁ。

ちょっと明日のWSの後とかで話しましょう 🙇

2022-08-31 09:24 UTC, nanashiki approved these changes
👍

2022-09-03 08:03 UTC, merged